### PR TITLE
converted underscore usage to lodash modules

### PR DESCRIPTION
**Pull request by hellatan**
@twhid @antialias - thoughts?

### CODE REVIEW

**Comment by hellatan** [comment]
i ran the tests locally and they passed. We should get this setup with travis ci for verification.

**Comment by antialias** [comment]
:+1:

**Comment by hellatan** [comment]
i'm going to add travis ci integration with this PR as well so please wait until I've added that before merging.

**Comment by hellatan** [comment]
the build is passing on my branch - https://travis-ci.org/hellatan/serverVars. This just needs to get hooked up to the 1stdibs account by @querybyexample but he's out for the next couple days. I'm open to getting this merged now and then just doing a quick patch once it's flipped on the 1stdibs account.

**Comment by twhid** [comment]
:ok: by me

**Comment by hellatan** [comment]
ok. gonna merge and then hook up the 1stdibs travis ci stuff later.

**Comment by hellatan** [comment]
whoops. It seems that I do not have access to merge this PR. @twhid or @antialias can one of you merge it? Not sure if you have access @antialias.

**Pull request merged**
